// examples/react-vite-ts/src/App.tsx
import { RevertConnect } from '@revertdotdev/revert-react';

function App() {
    return (
        <div
            style={{
                margin: '2rem',
                display: 'flex',
                justifyContent: 'center',
            }}
        >
            <RevertConnect
                config={{
                    revertToken: 'pk_test_Y2xlcmsuc3Ryb25nLmRlZXItNTYubGNsLmRldiQ',
                    tenantId: 'testTenantId',
                }}
            />
        </div>
    );
}

export default App;

// packages/vue/src/App.vue
<template>
  <div class="container">
    <RevertConnect :config="config" />
  </div>
</template>

<script>
import RevertConnect from './components/RevertConnect.vue';
export default {
  name: 'App',
  components: {
    RevertConnect,
  },
  data() {
    return {
      config: {
        revertToken: 'pk_test_Y2xlcmsuc3Ryb25nLmRlZXItNTYubGNsLmRldiQ',
        tenantId: 'testTenantId',
      },
    };
  },
};
</script>

<style scoped>
.container {
  margin: 2rem;
  display: flex;
  justify-content: center;
}
</style>
