// packages/my-lib/src/App.tsx
import styled from 'styled-components';
import MyButton from './lib/MyButton';

function App() {
    return (
        <Wrapper>
            <MyButton>Click me</MyButton>
        </Wrapper>
    );
}

const Wrapper = styled.div`
    margin: 2rem;
    display: flex;
    justify-content: center;
`;

export default App;

// packages/vue/src/App.vue
<template>
    <div class="container">
        <RevertConnect :config="config" />
    </div>
</template>

<script>
import RevertConnect from './components/RevertConnect.vue';
export default {
    name: 'App',
    components: {
        RevertConnect,
    },
    data() {
        return {
            config: {
                revertToken: 'localPublicToken',
                tenantId: null,
            },
        };
    },
};
</script>

<style scoped>
.container {
    margin: 2rem;
    display: flex;
    justify-content: center;
}
</style>
